"""initial

Revision ID: 6df4ff846734
Revises: 
Create Date: 2026-03-12 20:12:23.183923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df4ff846734'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('task_type', sa.Enum('SCRAPE_JOBS', 'ANALYZE_JOB', 'GENERATE_RESUME', 'GENERATE_COVER_LETTER', 'AUTO_APPLY', 'SEND_FOLLOW_UP', 'PREP_INTERVIEW', 'ANALYZE_MARKET', 'UPDATE_LINKEDIN', 'UPDATE_GITHUB', 'SEND_NOTIFICATION', name='agenttasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', 'CANCELLED', name='agenttaskstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('related_job_id', sa.String(length=36), nullable=True),
    sa.Column('related_application_id', sa.String(length=36), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index(op.f('ix_agent_tasks_created_at'), 'agent_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_related_job_id'), 'agent_tasks', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_task_type'), 'agent_tasks', ['task_type'], unique=False)
    op.create_table('application_events',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_created_at'), 'application_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_events_id'), 'application_events', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('cover_letter_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'QUEUED', 'APPLYING', 'APPLIED', 'VIEWED', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'REJECTED', 'WITHDRAWN', 'FAILED', name='applicationstatus'), nullable=False),
    sa.Column('method', sa.Enum('AUTO_BOT', 'EASY_APPLY', 'MANUAL', 'EMAIL', name='applicationmethod'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_score_at_apply', sa.Float(), nullable=True),
    sa.Column('job_title_snapshot', sa.String(length=500), nullable=True),
    sa.Column('company_snapshot', sa.String(length=255), nullable=True),
    sa.Column('recruiter_id', sa.String(length=36), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('recruiter_linkedin', sa.String(length=500), nullable=True),
    sa.Column('follow_up_status', sa.Enum('NONE', 'SCHEDULED', 'SENT', 'RESPONDED', name='followupstatus'), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('last_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('interview_feedback', sa.Text(), nullable=True),
    sa.Column('offer_salary', sa.Integer(), nullable=True),
    sa.Column('offer_details', sa.JSON(), nullable=True),
    sa.Column('bot_session_id', sa.String(length=100), nullable=True),
    sa.Column('bot_error', sa.Text(), nullable=True),
    sa.Column('bot_screenshot_path', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_recruiter_id'), 'applications', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('highlighted_skills', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_application_id'), 'cover_letters', ['application_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_created_at'), 'cover_letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_cover_letters_id'), 'cover_letters', ['id'], unique=False)
    op.create_index(op.f('ix_cover_letters_job_id'), 'cover_letters', ['job_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_table('generated_projects',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_gap_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('github_structure', sa.JSON(), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('github_repo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_projects_created_at'), 'generated_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_projects_id'), 'generated_projects', ['id'], unique=False)
    op.create_index(op.f('ix_generated_projects_user_id'), 'generated_projects', ['user_id'], unique=False)
    op.create_table('interviews',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('interview_type', sa.Enum('PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'SYSTEM_DESIGN', 'HR', 'FINAL', 'TAKE_HOME', name='interviewtype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('meeting_link', sa.String(length=2000), nullable=True),
    sa.Column('company_report', sa.JSON(), nullable=True),
    sa.Column('technical_questions', sa.JSON(), nullable=False),
    sa.Column('behavioral_questions', sa.JSON(), nullable=False),
    sa.Column('study_topics', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_created_at'), 'interviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('job_analyses',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('ats_keywords', sa.JSON(), nullable=False),
    sa.Column('min_years_experience', sa.Float(), nullable=True),
    sa.Column('max_years_experience', sa.Float(), nullable=True),
    sa.Column('education_requirement', sa.String(length=100), nullable=True),
    sa.Column('key_responsibilities', sa.JSON(), nullable=False),
    sa.Column('role_category', sa.String(length=100), nullable=True),
    sa.Column('seniority_detected', sa.String(length=50), nullable=True),
    sa.Column('is_internship', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_match_score', sa.Float(), nullable=True),
    sa.Column('semantic_similarity_score', sa.Float(), nullable=True),
    sa.Column('matching_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('skill_gap_count', sa.Integer(), nullable=False),
    sa.Column('estimated_applicants', sa.Integer(), nullable=True),
    sa.Column('competition_level', sa.String(length=20), nullable=True),
    sa.Column('interview_probability', sa.Float(), nullable=True),
    sa.Column('job_difficulty', sa.String(length=20), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('estimated_salary_min', sa.Integer(), nullable=True),
    sa.Column('estimated_salary_max', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analyses_created_at'), 'job_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_analyses_id'), 'job_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_job_analyses_job_id'), 'job_analyses', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_analyses_match_score'), 'job_analyses', ['match_score'], unique=False)
    op.create_table('jobs',
    sa.Column('source', sa.Enum('LINKEDIN', 'INDEED', 'INTERNSHALA', 'WELLFOUND', 'GLASSDOOR', 'COMPANY_SITE', 'MANUAL', name='jobsource'), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_logo_url', sa.String(length=2000), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('work_mode', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', 'UNKNOWN', name='workmode'), nullable=False),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', 'FREELANCE', name='jobtype'), nullable=False),
    sa.Column('experience_level', sa.Enum('ENTRY', 'MID', 'SENIOR', 'LEAD', 'UNKNOWN', name='experiencelevel'), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'QUEUED', 'APPLIED', 'SKIPPED', 'EXPIRED', name='jobstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applicant_count', sa.Integer(), nullable=True),
    sa.Column('easy_apply', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_source')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_work_mode'), 'jobs', ['work_mode'], unique=False)
    op.create_table('learning_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('weekly_plans', sa.JSON(), nullable=False),
    sa.Column('skills_addressed', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_plans_created_at'), 'learning_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_plans_id'), 'learning_plans', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plans_user_id'), 'learning_plans', ['user_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_jobs_scraped', sa.Integer(), nullable=False),
    sa.Column('total_jobs_analyzed', sa.Integer(), nullable=False),
    sa.Column('top_skills', sa.JSON(), nullable=False),
    sa.Column('top_companies_hiring', sa.JSON(), nullable=False),
    sa.Column('emerging_roles', sa.JSON(), nullable=False),
    sa.Column('salary_data', sa.JSON(), nullable=True),
    sa.Column('by_source', sa.JSON(), nullable=True),
    sa.Column('by_location', sa.JSON(), nullable=True),
    sa.Column('by_work_mode', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_created_at'), 'market_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_id'), 'market_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=False)
    op.create_table('mock_interview_sessions',
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('technical_depth_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=False),
    sa.Column('recording_path', sa.String(length=1000), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('filler_word_count', sa.Integer(), nullable=True),
    sa.Column('filler_words_detected', sa.JSON(), nullable=False),
    sa.Column('speech_pace_wpm', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_sessions_created_at'), 'mock_interview_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_id'), 'mock_interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_interview_id'), 'mock_interview_sessions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_user_id'), 'mock_interview_sessions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_reply_markup', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('recruiter_messages',
    sa.Column('recruiter_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_messages_created_at'), 'recruiter_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_recruiter_messages_id'), 'recruiter_messages', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_messages_recruiter_id'), 'recruiter_messages', ['recruiter_id'], unique=False)
    op.create_table('recruiters',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('interest_level', sa.String(length=20), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_company'), 'recruiters', ['company'], unique=False)
    op.create_index(op.f('ix_recruiters_created_at'), 'recruiters', ['created_at'], unique=False)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('resume_type', sa.Enum('BASE', 'TAILORED', 'ROLE_VARIANT', name='resumetype'), nullable=False),
    sa.Column('role_category', sa.String(length=100), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('keyword_coverage', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('target_job_id', sa.String(length=36), nullable=True),
    sa.Column('keywords_injected', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_is_active'), 'resumes', ['is_active'], unique=False)
    op.create_index(op.f('ix_resumes_resume_type'), 'resumes', ['resume_type'], unique=False)
    op.create_index(op.f('ix_resumes_target_job_id'), 'resumes', ['target_job_id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('demand_percentage', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('user_has_skill', sa.Boolean(), nullable=False),
    sa.Column('user_proficiency', sa.String(length=20), nullable=True),
    sa.Column('learning_plan_generated', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_created_at'), 'skill_gaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_gaps_id'), 'skill_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_user_id'), 'skill_gaps', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('experience_level', sa.Enum('ENTRY', 'MID', 'SENIOR', name='experiencelevel'), nullable=False),
    sa.Column('desired_roles', sa.JSON(), nullable=False),
    sa.Column('desired_locations', sa.JSON(), nullable=False),
    sa.Column('open_to_remote', sa.Boolean(), nullable=False),
    sa.Column('open_to_hybrid', sa.Boolean(), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=False),
    sa.Column('preferred_company_size', sa.JSON(), nullable=False),
    sa.Column('preferred_industries', sa.JSON(), nullable=False),
    sa.Column('avoid_companies', sa.JSON(), nullable=False),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('unique_value_proposition', sa.Text(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('work_experience', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('awards', sa.JSON(), nullable=False),
    sa.Column('publications', sa.JSON(), nullable=False),
    sa.Column('auto_apply_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_apply_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_apply_daily_limit', sa.Integer(), nullable=False),
    sa.Column('require_apply_approval', sa.Boolean(), nullable=False),
    sa.Column('notify_new_jobs', sa.Boolean(), nullable=False),
    sa.Column('notify_applications', sa.Boolean(), nullable=False),
    sa.Column('notify_interviews', sa.Boolean(), nullable=False),
    sa.Column('notify_via_telegram', sa.Boolean(), nullable=False),
    sa.Column('notify_via_email', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_session_cookie', sa.Text(), nullable=True),
    sa.Column('indeed_session_cookie', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_skills',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_skill')
    )
    op.create_index(op.f('ix_user_skills_created_at'), 'user_skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_created_at'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_skill_gaps_user_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_created_at'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_target_job_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_resume_type'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_is_active'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_created_at'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_company'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_recruiter_messages_recruiter_id'), table_name='recruiter_messages')
    op.drop_index(op.f('ix_recruiter_messages_id'), table_name='recruiter_messages')
    op.drop_index(op.f('ix_recruiter_messages_created_at'), table_name='recruiter_messages')
    op.drop_table('recruiter_messages')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mock_interview_sessions_user_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_interview_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_created_at'), table_name='mock_interview_sessions')
    op.drop_table('mock_interview_sessions')
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_created_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_learning_plans_user_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_created_at'), table_name='learning_plans')
    op.drop_table('learning_plans')
    op.drop_index(op.f('ix_jobs_work_mode'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_analyses_match_score'), table_name='job_analyses')
    op.drop_index(op.f('ix_job_analyses_job_id'), table_name='job_analyses')
    op.drop_index(op.f('ix_job_analyses_id'), table_name='job_analyses')
    op.drop_index(op.f('ix_job_analyses_created_at'), table_name='job_analyses')
    op.drop_table('job_analyses')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_created_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_generated_projects_user_id'), table_name='generated_projects')
    op.drop_index(op.f('ix_generated_projects_id'), table_name='generated_projects')
    op.drop_index(op.f('ix_generated_projects_created_at'), table_name='generated_projects')
    op.drop_table('generated_projects')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_job_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_created_at'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_application_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_recruiter_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_application_events_id'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_created_at'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_agent_tasks_task_type'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_related_job_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_created_at'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
