"""
app/agents/scrapers/linkedin.py
──────────────────────────────────
LinkedIn scraper — loads saved Playwright session (linkedin_session.json)
for authenticated access. Run save_session.py once to generate the file.
"""

from __future__ import annotations

import json
import pathlib
import re
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional

import httpx
from bs4 import BeautifulSoup

from app.agents.scrapers.base import BaseScraper, ScrapedJob
from app.core.config import settings

# Path to the session file saved by save_session.py
_SESSION_FILE = pathlib.Path(__file__).parents[3] / "linkedin_session.json"


def _load_session_cookies() -> dict:
    """
    Load cookies from the Playwright-saved session file.
    Returns an empty dict if the file doesn't exist yet — scraper will
    still work but with lower rate limits (public access only).
    """
    if not _SESSION_FILE.exists():
        return {}
    try:
        data = json.loads(_SESSION_FILE.read_text(encoding="utf-8"))
        return {c["name"]: c["value"] for c in data.get("cookies", [])}
    except Exception:
        return {}


class LinkedInScraper(BaseScraper):
    """
    Scrapes LinkedIn job listings using a saved browser session.
    Session is loaded from linkedin_session.json (generated by save_session.py).
    Falls back to public (unauthenticated) scraping if no session found.
    """

    source = "linkedin"
    BASE_URL = "https://www.linkedin.com"

    # Realistic browser headers — keeps requests looking human
    _HEADERS = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-origin",
    }

    async def _get_search_queries(self) -> List[Dict[str, Any]]:
        queries = []
        for role in settings.USER_DESIRED_ROLES:
            for location in settings.USER_DESIRED_LOCATIONS[:3]:
                queries.append({
                    "keywords": role,
                    "location": location,
                    "f_WT": "2" if location.lower() == "remote" else "",
                    "f_TPR": "r604800",  # Last 7 days
                })
        return queries

    async def _scrape_query(self, query_params: Dict) -> List[ScrapedJob]:
        jobs = []
        start = 0
        pages = 3  # 3 pages × 25 jobs = up to 75 jobs per search

        keywords = query_params["keywords"].replace(" ", "%20")
        location = query_params.get("location", "").replace(" ", "%20")

        # Load session cookies from saved file
        cookies = _load_session_cookies()
        if not cookies:
            self.log.warning(
                "No LinkedIn session found — using public access. "
                "Run save_session.py to authenticate."
            )

        async with httpx.AsyncClient(
            headers=self._HEADERS,
            cookies=cookies,
            follow_redirects=True,
            timeout=30,
        ) as client:
            for page in range(pages):
                url = (
                    f"{self.BASE_URL}/jobs/search?"
                    f"keywords={keywords}&location={location}"
                    f"&start={start}&f_TPR={query_params['f_TPR']}"
                )
                if query_params.get("f_WT"):
                    url += f"&f_WT={query_params['f_WT']}"

                try:
                    response = await client.get(url)

                    if response.status_code == 200:
                        page_jobs = self._parse_linkedin_page(response.text)
                        jobs.extend(page_jobs)
                        start += 25
                        if not page_jobs:
                            break  # No more results on this query
                        await self._sleep()

                    elif response.status_code == 429:
                        self.log.warning("LinkedIn rate limited — backing off 30s")
                        await self._sleep(extra=30.0)
                        break

                    elif response.status_code in (401, 403):
                        self.log.warning(
                            "LinkedIn session expired or invalid. "
                            "Re-run save_session.py to refresh."
                        )
                        break

                    else:
                        self.log.warning(
                            f"LinkedIn returned {response.status_code}",
                            url=url,
                        )
                        break

                except Exception as e:
                    self.log.error("LinkedIn page failed", error=str(e))
                    break

        return jobs

    def _parse_linkedin_page(self, html: str) -> List[ScrapedJob]:
        """Parse LinkedIn search results page into ScrapedJob objects."""
        soup = BeautifulSoup(html, "lxml")
        jobs = []

        cards = soup.find_all("div", class_=re.compile(r"job-search-card|base-card"))

        for card in cards:
            try:
                # Title
                title_el = (
                    card.find("h3", class_=re.compile(
                        r"job-search-card__title|base-search-card__title"
                    ))
                    or card.find("a", class_=re.compile(r"job-card-list__title"))
                )
                if not title_el:
                    continue
                title = title_el.get_text(strip=True)

                # Company
                company_el = card.find(
                    "h4", class_=re.compile(r"base-search-card__subtitle")
                )
                company = company_el.get_text(strip=True) if company_el else "Unknown"

                # Location
                loc_el = card.find(
                    "span", class_=re.compile(r"job-search-card__location")
                )
                location = loc_el.get_text(strip=True) if loc_el else ""

                # Job ID + URL
                link_el = card.find("a", href=re.compile(r"/jobs/view/"))
                if not link_el:
                    continue
                href = link_el.get("href", "")
                job_id_match = re.search(r"/jobs/view/(\d+)", href)
                if not job_id_match:
                    continue
                job_id = job_id_match.group(1)
                source_url = f"{self.BASE_URL}/jobs/view/{job_id}/"

                # Company logo
                img_el = card.find("img", class_=re.compile(r"artdeco-entity-image"))
                logo_url = img_el.get("data-delayed-url") if img_el else None

                # Applicant count
                count_el = card.find(
                    "span", class_=re.compile(r"job-search-card__applicant-count")
                )
                applicant_count = None
                if count_el:
                    m = re.search(r"(\d+)", count_el.get_text())
                    if m:
                        applicant_count = int(m.group(1))

                # Posted date
                posted_at = None
                date_el = card.find("time")
                if date_el:
                    dt_str = date_el.get("datetime")
                    if dt_str:
                        try:
                            posted_at = datetime.fromisoformat(
                                dt_str.replace("Z", "+00:00")
                            )
                        except ValueError:
                            pass

                jobs.append(ScrapedJob(
                    source=self.source,
                    source_job_id=f"li_{job_id}",
                    source_url=source_url,
                    title=title,
                    company_name=company,
                    location=location,
                    work_mode=self._detect_work_mode(location + " " + title),
                    job_type=self._detect_job_type(title),
                    posted_at=posted_at,
                    applicant_count=applicant_count,
                    company_logo_url=logo_url,
                    easy_apply=False,
                ))

            except Exception as e:
                self.log.warning("LinkedIn card parse failed", error=str(e))

        return jobs